### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by Rico1502** [faassen/rust-it8951#4]
Hi @faassen, we were on the search for a Rust version of the USB connection for the IT8951 and found your project, which worked out of the box for us!
Unfortunately this project has no license, therefore we are not allowed to use it as a dependency.

Is it ok to extend this project with a license? I'd add this and give you a pull request if it is fine by you?

**Comment by faassen** [comment]
An oversight on my part, sorry! If you could add a PR with an MIT license I will merge it, thank you!

**Comment by Rico1502** [comment]
Thank you!
